
## DB config goes here
spring:
  batch:
    jdbc:
      initialize-schema: always
  output:
    ansi:
      enabled: always
  sql:
    init:
    mode: always

  datasource:
    url: jdbc:postgresql://localhost:5432/forecastdb
    username: forecast
    password: secret
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    #    database-platform: org.hibernate.dialect.PostgreSQLDialect

    ## Logging settings
debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR