spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/forecastdb
    username: forecast
    password: secret
    output:
      ansi:
        enabled: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

logging:
  level:
    root: INFO
    com.samimu7.startorbench: DEBUG

debug: true


